/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#00685f',
        'on-primary': '#ffffff',
        'primary-container': '#008378',
        'on-primary-container': '#f4fffc',
        secondary: '#855300',
        'on-secondary': '#ffffff',
        'secondary-container': '#fea619',
        'on-secondary-container': '#684000',
        tertiary: '#3e57a8',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5870c3',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#3d4947',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        outline: '#6d7a77',
        'outline-variant': '#bcc9c6',
      },
      fontFamily: {
        'display-lg': ['"IBM Plex Sans Arabic"', 'sans-serif'],
        'headline-lg': ['"IBM Plex Sans Arabic"', 'sans-serif'],
        'headline-md': ['"IBM Plex Sans Arabic"', 'sans-serif'],
        'body-lg': ['"IBM Plex Sans Arabic"', 'sans-serif'],
        'body-md': ['"IBM Plex Sans Arabic"', 'sans-serif'],
        'label-md': ['"IBM Plex Sans Arabic"', 'sans-serif'],
        caption: ['"IBM Plex Sans Arabic"', 'sans-serif'],
        arabic: ['"IBM Plex Sans Arabic"', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'section-gap': '64px',
      },
    },
  },
  plugins: [],
};
